export const EDITOR_LAYER = 0;
export const RENDER_LAYER = 1;
export const INTERSECTION_LAYER = 2;
export const BACKGROUND_LAYER = 5; // Layer for objects not visible in tree view
export const DEFAULT_SCENE_COLOR = "#6d6d6d";
export const ROOT_ID = -1000;
export const DEFAULT_LINE_WIDTH = 10;
export const DEFAULT_LINE_OFFSET = 0.05;
export const DEFAULT_KEYFRAME_DURATION = 250;
export const DEFAULT_FPS = 24;
export const DEFAULT_LOOP_SETTING = true;
export const MAIN_MESH_RENDER_ORDER = 0;
